services:
  postgres:
    image: bitnami/postgresql:latest
    ports:  
      - '5432:5432'
    container_name: unitasker_db
    restart: unless-stopped
    environment:
      - POSTGRESQL_USER=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_NAME}
    volumes:
      - unitasker_pg_data:/bitnami/postgresql

  backend:
    build: .  
    container_name: unitasker_backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
    #Backend quebra se n esperar um pouco pro banco de dados iniciar :)
    command: /bin/sh -c "sleep 5 && python seed.py && exec gunicorn -k eventlet -w 2 -b 0.0.0.0:5000 app:app"
    depends_on:
      - postgres
    volumes:
      #Volume de uploads para eles persistirem após um build do backend 
      - unitasker_uploads:/app/static/images/uploads


  caddy:
    image: caddy:latest
    container_name: unitasker_proxy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend

volumes:
  unitasker_pg_data:
  caddy_data:
  caddy_config:
  unitasker_uploads: