"""Migrando banco

Revision ID: a7229aa69c33
Revises: 
Create Date: 2025-12-02 11:17:27.395234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7229aa69c33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario_portfolio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cover', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario_portfolio', schema=None) as batch_op:
        batch_op.drop_column('is_cover')

    # ### end Alembic commands ###
